In [1]:
const ○ = 1 # 𝟘 ○ OF
const ● = 2 # 𝟙 ● ON

2

https://github.com/Jutho/SparseArrayKit.jl

https://github.com/wmayner/pyphi
https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pcbi.1006343/2/pcbi.1006343.s001.pdf

In [25]:
state_count = 4

# state by state flat 
p = 
Float64[
#              ○ ● ○ ● ○ ● ○ ● ○ ● ○ ● ○ ● ○ ●
#              ○ ○ ● ● ○ ○ ● ● ○ ○ ● ● ○ ○ ● ●
#              ○ ○ ○ ○ ● ● ● ● ○ ○ ○ ○ ● ● ● ●
#              ○ ○ ○ ○ ○ ○ ○ ○ ● ● ● ● ● ● ● ●    
#= ○ ○ ○ ○ =#  1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
#= ● ○ ○ ○ =#  0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0;
#= ○ ● ○ ○ =#  0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0;
#= ● ● ○ ○ =#  0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
#= ○ ○ ● ○ =#  0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
#= ● ○ ● ○ =#  0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0;
#= ○ ● ● ○ =#  0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0;
#= ● ● ● ○ =#  0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0;
#= ○ ○ ○ ● =#  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0;
#= ● ○ ○ ● =#  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0;
#= ○ ● ○ ● =#  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0;
#= ● ● ○ ● =#  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0;
#= ○ ○ ● ● =#  0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0;
#= ● ○ ● ● =#  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;
#= ○ ● ● ● =#  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0;
#= ● ● ● ● =#  0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0;
]
q = reshape(p, (ntuple(x->2, state_count*2)));

In [3]:
#programatically access row with variable state count
index = (ntuple(x->●, state_count)..., ntuple(x->Colon(), state_count)...)
q[index...]
reshape(q[index...], (1,state_count^2))

1×16 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  1.0  0.0  0.0  0.0  0.0

In [4]:
reshape(q[●,○,○,○,:,:,:,:], (1,16)) # extract row

1×16 Matrix{Float64}:
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [5]:
reshape(q[:,:,:,:,●,○,○,○], (16,1)) # extract column

16×1 Matrix{Float64}:
 0.0
 0.0
 0.0
 1.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [6]:
reshape(q, 16, 16)

16×16 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  1.0  1.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

In [24]:
q2 = q[:,:,:,○,:,:,:,:] # fixing background conditions
reshape(q[:,:,:,○,:,:,:,:], 8, 16)#visual aid

8×16 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  1.0  1.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [11]:
q3 = q2[:,:,:,:,:,:,○] + q2[:,:,:,:,:,:,●] # marganalizing out state
reshape(q3, 8, 8) 

8×8 Matrix{Float64}:
 1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

In [14]:
q4 = q2 ./ sum(q2, dims=(4,5,6,7)) # normailizing rows
reshape(q4, 8, 16) 
# (4,5,6,7) are all the dimensions representing t+1 states
# reshaping is just for visual clarity here

8×16 Matrix{Float64}:
 0.25  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.25  0.25  0.0  0.0  0.0  0.0
 0.0   0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0   0.0   0.0  0.0  0.0  0.0
 0.0   0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0   0.0   0.0  0.0  0.0  0.0
 0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0   0.0   0.0  0.0  0.0  0.0
 0.0   1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0   0.0   0.0  0.0  0.0  0.0
 0.0   0.0  0.0  0.0  0.0  0.0  0.0  1.0  …  0.0   0.0   0.0  0.0  0.0  0.0
 0.0   0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0   0.0   0.0  0.0  0.0  0.0
 0.0   0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0   0.0   0.0  0.0  0.0  0.0

In [6]:
# candidate system ABC fixing D
q2 = q[:,:,:,○,:,:,:,:] # fixing background condition D at t
q3 = q2[:,:,:,:,:,:,○] + q2[:,:,:,:,:,:,●] # marganalizing out state D at t+1
q4 = q3 ./ sum(q3, dims=(4,5,6)) # normailizing rows
reshape(q4, 8, 8) 

8×8 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

In [28]:
# Mechanism C over purview BC

# Feed in a uniform distribution to A's inputs

q5 = q4[:,:,:,:,○,:] + q4[:,:,:,:,●,:] # marganilize out B at t+1
q6 = q5 ./ sum(q5, dims=(4,5)) # normailizing rows

q7 = q6[:,:,:,:,○] + q6[:,:,:,:,●] # marganilize out C at t + 1
q8 = q7 ./ sum(q7, dims=(4)) # normailizing rows

q9 = q8[○,:,:,:] + q8[●,:,:,:] # marganilize out A at t - 1
q10 = q9 ./ sum(q9, dims=(3)) # normailizing rows

q11 = q10[○,:,:] + q10[●,:,:] # marganilize out B at t - 1
q12 = q11 ./ sum(q11, dims=(2)) # normailizing rows

q13 = q12[○,:] + q12[●,:] # marganilize out C at t - 1
q14 = q13 ./ sum(q13, dims=(1)) # normailizing rows


2-element Vector{Float64}:
 0.25
 0.75